//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_1.h
//   Version: 1.2, Updated on 2008/6/23 at 12:24:56                                          
//  Generated by PSoC Designer ???
//
//  DESCRIPTION: LED_1 User Module C Language interface file
//               for the (22/24/26/27/29xxx) PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2005. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_1_Stop
#pragma fastcall16  LED_1_Start
#pragma fastcall16  LED_1_On
#pragma fastcall16  LED_1_Off
#pragma fastcall16  LED_1_Switch
#pragma fastcall16  LED_1_Invert
#pragma fastcall16  LED_1_GetState


//-------------------------------------------------
// Constants for LED_1 API's.
//-------------------------------------------------
//
#define  LED_1_ON   1
#define  LED_1_OFF  0

//-------------------------------------------------
// Prototypes of the LED_1 API.
//-------------------------------------------------
extern void  LED_1_Start(void);                                     
extern void  LED_1_Stop(void);                                      
extern void  LED_1_On(void);                                      
extern void  LED_1_Off(void);                                      
extern void  LED_1_Switch(BYTE bSwitch);
extern void  LED_1_Invert(void);                                         
extern BYTE  LED_1_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------




